#!/usr/bin/env bash

for repeat in 1 2 3
do
for concurrency in 1000 750 500 250
do
for length in 150 100 50
do
for item in so
do
    echo "Running $item with $length and concurrency $concurrency"
    ab -s 45 -H "Accept-Encoding: gzip" -n 25000 -c $concurrency "http://198.58.97.4:42068/?name=$item&str=foo&len=$length" >> ./data/`echo $item`_`echo $length`_`echo $concurrency`

    # allows for manual execution of gc
    echo "done -- sleeping"
    sleep 3
done
done
done
done

