#!/usr/bin/env node

const path = require("path");
const fs = require("fs");
const folder = process.argv[2];

const stats = fs.statSync(folder);

if (stats.isFile()) {
    throw new Error("must be directory");
    console.log("File");
}

const files = fs.readdirSync(folder);
const lengths = [50, 250, 500, 1000, 2500, 5000, 10000];
const names = ["native", "buffer", "secialCase", "leftPadEmber", "leftPadTravvy", "leftPad"];
const concurrencies = [250, 500, 750, 1000, 2000];
const dataPoints = [];
const data = [];

for (let i = 0; i < concurrencies.length; ++i) {
    for (let j = 0; j < names.length; ++j) {
        dataPoints.push(`${names[j]}_${concurrencies[i]}`);
        data.push([]);
    }
}

for (const file of files) {
    const [
        name,
        length,
        concurrency,
    ] = file.split("_");

    if (!name || !concurrency || !length) {
        continue;
    }

    const lengthIdx = lengths.indexOf(+length);
    const nameIdx = dataPoints.indexOf(`${name}_${concurrency}`);

    if (lengthIdx === -1 || nameIdx === -1) {
        continue;
    }

    const filePath = path.join(folder, file);
    const contents = fs.readFileSync(filePath, "utf8").toString().split("\n");
    const totals = contents.filter(line => line.includes("Total:"));

    let sum = 0;
    for (const total of totals) {
        const [, med, _] = total.split(" ").map(x => +x).filter(x => x);
        sum += med;
    }

    data[nameIdx][lengthIdx] = sum / totals.length || 0;
}

function getConcurrencyRow(concurrency) {
    const row = [];
    for (const name of names) {
        row.push(`${name}_${concurrency}`);
    }
    return row;
}

function printOut(concurrency) {
    const test = getConcurrencyRow(concurrency);
    const out = [
        ["", ...test].join(","),
    ]
    for (const length of lengths) {
        const row = [length];
        for (const name of test) {
            const idx = dataPoints.indexOf(name);
            row.push(Math.round(data[idx][lengths.indexOf(length)]));
        }
        out.push(row.join(","));
    }

    for (const o of out) {
        if (o.includes("NaN")) {
            continue;
        }
        console.log(o);
    }
}

for (const concurrency of concurrencies) {
    printOut(concurrency);
    console.log();
}

